default:
  image: node:23.7.0

stages:
  - check
  - deploy

tsc_check:
  stage: check
  script:
    - npm install
    - npx tsc --noEmit
  only:
    - merge_requests
  except:
    - main

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - mkdir -p .vercel
    - echo "{\"projectId\":\"$VERCEL_PROJECT_ID\",\"orgId\":\"$VERCEL_ORG_ID\"}" > .vercel/project.json
    - vercel pull --yes --environment=preview
    - vercel build
    - vercel deploy --prebuilt

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production
    - vercel build --prod
    - vercel deploy --prebuilt --prod